// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMgJBg9lifY7IVMWy26QS8cOQABMbBUVQ',
    appId: '1:810630674008:android:296631e3780ca164013c2d',
    messagingSenderId: '810630674008',
    projectId: 'budget-buddy-app-ecf8b',
    storageBucket: 'budget-buddy-app-ecf8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYtHbZ2DisxOBXoW8kHNrBizYcZwgdPnI',
    appId: '1:810630674008:ios:40c7c6d03967c2a9013c2d',
    messagingSenderId: '810630674008',
    projectId: 'budget-buddy-app-ecf8b',
    storageBucket: 'budget-buddy-app-ecf8b.firebasestorage.app',
    androidClientId: '810630674008-0n7ngpfmgrsld302odhvpkqesp80ormf.apps.googleusercontent.com',
    iosClientId: '810630674008-0mjadebc28ouhu6s3627tf24aaaph457.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetBuddyApp',
  );
}
